"""empty message

Revision ID: be38ca76d275
Revises: 
Create Date: 2025-03-02 15:37:54.694942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be38ca76d275'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('clues', sa.PickleType(), nullable=False),
    sa.Column('fun_fact', sa.PickleType(), nullable=False),
    sa.Column('trivia', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('challenge',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inviter_username', sa.String(length=50), nullable=False),
    sa.Column('invitee_username', sa.String(length=50), nullable=True),
    sa.Column('inviter_score', sa.Integer(), nullable=False),
    sa.Column('invitee_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invitee_username'], ['user.username'], ),
    sa.ForeignKeyConstraint(['inviter_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge')
    op.drop_table('user')
    op.drop_table('destination')
    # ### end Alembic commands ###
